apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: annms-argocd
  namespace: argocd
spec:
  project: default
  source:
    chart: argo/argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 4.8.2
    
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true